on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: petejohanson/zmk/.github/workflows/build-user-config.yml@feat/pointers-move-scroll
      #uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
